{{- if .Values.apiServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes-operator.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hermes-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.apiServer.port }}
    targetPort: api
    protocol: TCP
    name: api
  selector:
    control-plane: controller-manager
    {{- include "hermes-operator.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.prometheus.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hermes-operator.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.prometheus.serviceMonitor.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.metricsPort }}"
    prometheus.io/path: "/metrics"
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    control-plane: controller-manager
    {{- include "hermes-operator.selectorLabels" . | nindent 4 }}
{{- end }}
